### PR TITLE
rtos: Fix reading Zephyr thread name and update debug symbol names

### PR DESCRIPTION
**Pull request by MaureenHelm**
- Fixes an issue reading Zephyr thread names caused by a change in how Zephyr stores them (one less level of indirection). This issue has been present for a very long time, since Zephyr v2.0.0 (released Sep 7 2019).

- Updates the Zephyr debug symbol names to reflect that they are no longer specific to OpenOCD. The old symbols were deprecated in Zephyr v2.6.0 (released Jun 4 2021) and will be removed after two releases.

Tested with Zephyr v2.7.0 `samples/philosophers` on `frdm_k64f`

Before this PR:
```
(gdb) i thr
  Id   Target Id                                  Frame 
* 2    Thread 536872064 (Running; Priority 40)    arch_cpu_idle () at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/cpu_idle.S:107
  3    Thread 536871888 (Suspended; Priority 254) arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  4    Thread 536871712 (Suspended; Priority 255) arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  5    Thread 536871536 (Suspended; Priority 0)   arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  6    Thread 536871360 (Suspended; Priority 1)   arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  7    Thread 536871184 (Suspended; Priority 2)   arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  8    Thread 536871008 (Suspended; Priority 3)   arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
```
After:
```
(gdb) i thr
  Id   Target Id                                                  Frame 
* 2    Thread 536872064 "idle 00" (Running; Priority 40)          arch_cpu_idle () at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/cpu_idle.S:107
  3    Thread 536871888 "Philosopher 5" (Suspended; Priority 254) arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  4    Thread 536871712 "Philosopher 4" (Pending; Priority 255)   arch_swap (key=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  5    Thread 536871536 "Philosopher 3" (Suspended; Priority 0)   arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  6    Thread 536871360 "Philosopher 2" (Suspended; Priority 1)   arch_swap (key=key@entry=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  7    Thread 536871184 "Philosopher 1" (Pending; Priority 2)     arch_swap (key=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
  8    Thread 536871008 "Philosopher 0" (Pending; Priority 3)     arch_swap (key=0) at /home/mhelm/zephyrproject/zephyr/arch/arm/core/aarch32/swap.c:53
```

### CODE REVIEW

**Comment by flit** [comment]
Hi @MaureenHelm, apologies for not getting this into the v0.33 release! I was so focused on testing and getting the release out that I didn't check for new PRs. 😞 I'll release a patch update within a few weeks that includes this.

**Review by flit — CHANGES_REQUESTED** [review]
The code itself is fine, but could you please add an appropriate copyright to the file header?

**Comment by MaureenHelm** [comment]
> The code itself is fine, but could you please add an appropriate copyright to the file header?

Sure, done.

**Review by flit — APPROVED** [review]

**Comment by flit** [comment]
Thanks!

**Comment by DariusBabrauskas** [comment]
Hello @MaureenHelm,
  Please review my issue #1470.
BR.

**Pull request merged**
