### PR TITLE
Add Basic SEGGER RTT Real Time Transfer Support.

### PR DESCRIPTION
**Pull request by mikisama**
pyocd_rtt

The basic functions works. 😀

### CODE REVIEW

**Comment by ccattuto** [comment]
This is great. Do you plan to add support for up buffers, as well?

**Comment by flit** [comment]
@ccattuto Yes, and better integration throughout pyocd. #1241 captures a number of ideas for improvement. Any help would be appreciated! 😉

**Comment by ccattuto** [comment]
Here's an initial PR for host-to-target RTT transfer: https://github.com/pyocd/pyOCD/pull/1253#issue-1067741845
It's meant to demonstrate how things could work, with RTT bidirectional transfer offering terminal-like communication to the target. It could be useful, maybe, to inform decisions on refactoring the RTT subcommand implementation.

**Comment by flit** [comment]
That's great, thanks for the addition. 😄

**Pull request merged**
