### PR TITLE
Switch from naturalsort to natsort

### LINKED ISSUE #1317: Replace naturalsort dependency with natsort or remove altogether
Hi! I'm about to package this project for Arch Linux (due to other dependencies).

Unfortunately the [naturalsort](https://github.com/xolox/python-naturalsort) upstream seems very dead, [does conflict with natsort](https://github.com/xolox/python-naturalsort/issues/4) (which is actively maintained and already packaged on Arch Linux), has less features and thus seems less fit for being included in any upstream project.
It would be very cool if you could switch to using natsort, or remove the necessity of naturalsort altogether, which seems to be only required for this command:
https://github.com/pyocd/pyOCD/blob/7d164d99e816c4ef6c99f257014543188a0ca5a6/pyocd/commands/commands.py#L119-L120

### PR DESCRIPTION
**Pull request by dvzrv**
pyocd/commands/commands.py:
Use natsort's `natsorted()` instead of naturalsort's `natsort()`.

setup.cfg:
Replace naturalsort with natsort.

Fixes #1317

### CODE REVIEW

**Review by flit — APPROVED** [review]
Since it's only a 2 line change in the .py file, I won't make it a strict requirement that you add your copyright to the file header, but it would be nice.

**Comment by dvzrv** [comment]
> 

Sure, I can add it, no problem.

I hope my change works as intended!

**Comment by flit** [comment]
Thanks!

I just did a quick test, and it works as expected. 👍🏽

**Pull request merged**
