### PR TITLE
Feature/enable imxrt1170

### PR DESCRIPTION
**Pull request by jhqian**
Add support for RT1170

### CODE REVIEW

**Comment by flit** [comment]
Thanks @jhqian!

**Review by flit — CHANGES_REQUESTED** [review]
Would you mind cleaning up the unused imports? 
You can see the LGTM report for this PR here (you'll have to click to expand the diff for  `target_MIMXRT11176xxxxx.py`):
https://lgtm.com/projects/g/pyocd/pyOCD/rev/pr-91343de83900de8e0e193ed95e0ed69b525cb9a7

**Comment by jhqian** [comment]
Sure, @flit , just fixed.

**Pull request merged**
